# Name for the data plane.
# If you have multiple data-planes, provide a distinguish name for each.
name: iomete-data-plane1

database:
  type: postgresql
  host: "postgresql"
  port: "5432"
  user: "iomete_user"
  password: "iomete_pass"
  prefix: "iomete_" # all IOMETE databases should be prefixed with this. See database init script.
  defaultSchema: public
  adminCredentials:
    user: "postgres"
    password: "onXB8UbEqYzkQFgbXe8F#C5ckmyKix&"
  ssl:
    enabled: false # Enabling this will require javaTrustStore to be enabled and configured properly
    mode: "disable" # disable, verify-full

istioGateway:
  tlsCertSecretName: ""
  host: "*"

storage:
  lakehouseBucketName: "lakehouse"
  assetsBucketName: "assets"
  # minio, dell_ecs, aws_s3, gcs, azure_gen1, azure_gen2
  type: "minio"
  minioSettings:
    endpoint: "http://minio.default.svc:9000"
    accessKey: "admin"
    secretKey: "password"

clusterDomain: cluster.local

helmRepo:
  url: "https://chartmuseum.iomete.com"
  type: "default"
  secretRef: ""

docker:
  repo: iomete
  pullPolicy: Always
  appVersion: 1.8.0
  sparkVersion: 3.5.1
  imagePullSecrets: []

dataCatalog:
  enabled: true
  storageSize: 1Gi

opa:
  enabled: true

# Data Security
ranger:
  enabled: true

jupyterGateway:
  authToken: "changeit"
  kernels:
    - pyspark_kernel
    - spark_scala_kernel

javaTrustStore:
  enabled: false
  secretName: java-truststore # Name of the secret with the truststore.jks file
  fileName: truststore.jks
  password: changeit
  mountPath: /etc/ssl/certs