apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: istio
spec:
  interval: 1m
  url: https://istio-release.storage.googleapis.com/charts

---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istio-base
spec:
  interval: 10m
  releaseName: base
  chart:
    spec:
      chart: base
      version: 1.17.2
      sourceRef:
        kind: HelmRepository
        name: istio
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istiod
spec:
  dependsOn:
    - name: istio-base
  interval: 10m
  releaseName: istiod
  chart:
    spec:
      chart: istiod
      version: 1.17.2
      sourceRef:
        kind: HelmRepository
        name: istio
  values:
    global:
      defaultPodDisruptionBudget:
        enabled: false
    meshConfig:
      accessLogFile: "/dev/stdout"

---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istio-ingress
spec:
  dependsOn:
    - name: istio-base
    - name: istiod
  interval: 10m
  releaseName: istio-ingress
  chart:
    spec:
      chart: gateway
      version: 1.17.2
      sourceRef:
        kind: HelmRepository
        name: istio
  values:
    service:
      # Type of service. Set to "None" to disable the service entirely
      type: LoadBalancer
      ports:
        - name: status-port
          port: 15021
          protocol: TCP
          targetPort: 15021
        - name: http2
          port: 80
          protocol: TCP
          targetPort: 80
        - name: https
          port: 443
          protocol: TCP
          targetPort: 443
      annotations: { }
      loadBalancerIP: ""
      loadBalancerSourceRanges: [ ]
      externalTrafficPolicy: ""
      externalIPs: [ ]