meshConfig:
  extensionProviders:
    # The name "my-ext-authz-service" is referred to by the authorization policy in its provider field.
    - name: "iomete-authz-service"
      # The "envoyExtAuthzGrpc" field specifies the type of the external authorization service is implemented by the Envoy
      # ext-authz filter gRPC API. The other supported type is the Envoy ext-authz filter HTTP API.
      # See more in https://www.envoyproxy.io/docs/envoy/v1.16.2/intro/arch_overview/security/ext_authz_filter.
      envoyExtAuthzHttp:
        # The service and port specifies the address of the external auth service, "ext-authz.istio-system.svc.cluster.local"
        # means the service is deployed in the mesh. It can also be defined out of the mesh or even inside the pod as a separate
        # container.
        service: "iom-identity.iomete-system.svc.cluster.local"
        port: 80
        includeRequestHeadersInCheck: ["cluster", "user-id", "api-token" ]
        pathPrefix: "/api/v1/iam/connect/authz"