auth:
  enablePostgresUser: true
  postgresPassword: "onXB8UbEqYzkQFgbXe8F#C5ckmyKix&"

primary:
  persistence:
    enabled: true
    accessModes:
      - ReadWriteOnce
    size: 8Gi
  extendedConfiguration: |
    max_connections=500
  podAnnotations:
    sidecar.istio.io/inject: "false" # Disable sidecar injection

backup:
  enabled: false