auth:
  enablePostgresUser: true
  postgresPassword: "onXB8UbEqYzkQFgbXe8F#C5ckmyKix&"

primary:
  persistence:
    enabled: true
    accessModes:
      - ReadWriteOnce
    size: 8Gi

backup:
  enabled: false
