{
 "title": "IOMETE - Spark Job Metrics",
 "tags": [ "iomete" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(metrics_executor_memoryUsed_bytes,namespace)"
    }
   },
   {
    "name": "driver_pod",
    "label": "Driver Pod Name",
    "query": {
     "query": "label_values(metrics_executor_memoryUsed_bytes{namespace=\"$namespace\"},pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Executors",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "count(metrics_executor_memoryUsed_bytes{\n  namespace=\"$namespace\", \n  executor_id!=\"driver\", \n  pod=\"$driver_pod\"\n}) by (application_id)",
     "legendFormat": "app={{application_name}} executor={{executor_id}}"
    }
   ]
  },
  {
   "title": "Total Completed Tasks",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(metrics_executor_completedTasks_total{\n    namespace=\"$namespace\", \n    executor_id!=\"driver\", \n    pod=\"$driver_pod\"\n})"
    }
   ]
  },
  {
   "title": "Total Failed Tasks",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(metrics_executor_failedTasks_total{\n    namespace=\"$namespace\", \n    pod=\"$driver_pod\",\n    executor_id!=\"driver\"\n})",
     "legendFormat": "app={{application_name}} executor={{executor_id}}"
    }
   ]
  },
  {
   "title": "Total GC time",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(metrics_executor_totalGCTime_seconds_total{\n    namespace=\"$namespace\", \n    pod=\"$driver_pod\"\n})"
    }
   ]
  },
  {
   "title": "Total Tasks Time per Executor",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(metrics_executor_totalDuration_seconds_total{\n    namespace=\"$namespace\", \n    pod=\"$driver_pod\"\n}) by (executor_id)",
     "legendFormat": "{{executor_id}}"
    }
   ]
  },
  {
   "title": "Total Tasks per Executor",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(metrics_executor_totalTasks_total{\n    namespace=\"$namespace\", \n    pod=\"$driver_pod\",\n    executor_id!=\"driver\"\n}) by (executor_id)",
     "legendFormat": "{{executor_id}}"
    }
   ]
  },
  {
   "title": "Executor GC time",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(metrics_executor_totalGCTime_seconds_total{\n    namespace=\"$namespace\", \n    pod=\"$driver_pod\"\n}[1m])",
     "legendFormat": "executor={{executor_id}}"
    }
   ]
  },
  {
   "title": "Active Tasks per Executor",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "expr": "metrics_executor_activeTasks{\n    namespace=\"$namespace\", \n    pod=\"$driver_pod\"\n}",
     "legendFormat": "executor={{executor_id}}"
    }
   ]
  },
  {
   "title": "Shuffle Bytes Read",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(metrics_executor_totalShuffleRead_bytes_total{\n    namespace=\"$namespace\", \n    pod=\"$driver_pod\"\n}[5m])",
     "legendFormat": "executor={{executor_id}}"
    }
   ]
  },
  {
   "title": "Shuffle Bytes Written",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(metrics_executor_totalShuffleWrite_bytes_total{\n    namespace=\"$namespace\", \n    pod=\"$driver_pod\"\n}[5m])",
     "legendFormat": "executor={{executor_id}}"
    }
   ]
  },
  {
   "title": "Memory Used",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "metrics_executor_memoryUsed_bytes{\n    namespace=\"$namespace\", \n    pod=\"$driver_pod\"\n}",
     "legendFormat": "executor={{executor_id}}"
    }
   ]
  }
 ]
}