cloud:
  provider: on-prem
  region: us-east

dataPlane:
  adminUser:
    username: "admin"
    email: "admin@example.com" # required for password reset
    firstName: Admin
    lastName: Admin
    temporaryPassword: "admin" # you will be prompted to change this on first login

istioGateway:
  # if you want to enable TLS, set the tlsCertSecretName
  # name of the secret with certificates. Secret should contain 2 files: tls.crt and tls.key
  # if redirectHttpToHttps is set to true, this secret must be provided to handle https traffic
  tlsCertSecretName: ""

spark:
  logLevel: warn

jupyter:
  authToken: "eg_AIm8b2G4BOJ79da6"

keycloak:
  enabled: true
  adminUser: "kc_admin"
  adminPassword: "Admin_123"
  # if adminPasswordSecret is set, the password will be read from the secret
  adminPasswordSecret: {}
    # name: secret-name
    # key: password
  endpoint: "http://keycloak-http/auth"

storage:
  catalogs:
    spark_catalog:
      bucketName: "lakehouse"
  assetsBucketName: "assets"
  # minio, dell_ecs, aws_s3, gcs, azure_gen1, azure_gen2
  type: "minio"
  minioSettings:
    endpoint: "http://minio.default.svc.cluster.local:9000"
    accessKey: "admin"
    secretKey: "password"
    # if secretKeySecret is set, the secretKey will be read from the secret
    secretKeySecret: {}
      # name: secretName
      # key: secretKey
    additionalConfigOverrides: {}
      # core-site-xml-overrides: |
        # fs.s3a.path.style.access: true
        # fs.s3a.connection.ssl.enabled: false

database:
  host: "mysql"
  port: "3306"
  user: "iomete_user"
  password: "iomete_pass"
  # if passwordSecret is set, the password will be read from the secret
  passwordSecret: {}
    # name: byo-db-creds
    # key: password
  prefix: "iomete_" # all IOMETE databases should be prefixed with this. See database init script.

  # Provide database admin credentials to create the IOMETE databases,
  # otherwise please run the database init script manually. See: files/database-init.sql
  adminCredentials:
    user: "root"
    password: "onXB8UbEqYzkQFgbXe8F#C5ckmyKix&"
    # if passwordSecret is set, the password will be read from the secret
    passwordSecret: {}
      # name: byo-db-creds
      # key: password


clusterDomain: cluster.local

ranger:
  enabled: true

# Enabled if you have multiple data-planes, and you need control-plane for SSO and other features
controlPlane:
  enabled: false
  
  # You can use the same database as data-plane, or use separate database
  database: {}
    # host: "mysql"
    # port: "3306"
    # user: "iomete_user"
    # password: "iomete_pass"
    # # if passwordSecret is set, the password will be read from the secret
    # passwordSecret: {}
    #   # name: byo-db-creds
    #   # key: password
    # prefix: "iomete_" # all IOMETE databases should be prefixed with this. See database init script.
    #
    # # Provide database admin credentials to create the IOMETE databases, otherwise please run the database init script manually.
    # adminCredentials: {}
    #   # user: "root"
    #   # password: "onXB8UbEqYzkQFgbXe8F#C5ckmyKix&"
    #   # # if passwordSecret is set, the password will be read from the secret
    #   # passwordSecret: {}
    #   #   # name: byo-db-creds
    #   #   # key: password