apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: iomete-istio
spec:
  interval: 5m
  releaseName: iomete-istio
  targetNamespace: istio-system
  install:
    createNamespace: true
  chart:
    spec:
      chart: iomete-istio
      version: 2.2.5
      sourceRef:
        kind: HelmRepository
        name: iomete
  values:
    gateway:
      service:
        # Type of service. Set to "None" to disable the service entirely
        type: LoadBalancer
        ports:
          - name: status-port
            port: 15021
            protocol: TCP
            targetPort: 15021
          - name: http2
            port: 80
            protocol: TCP
            targetPort: 80
            nodePort: 30080
          - name: https
            port: 443
            protocol: TCP
            targetPort: 443
            nodePort: 30443
        annotations: { }
        loadBalancerIP: ""
        loadBalancerSourceRanges: [ ]
        externalTrafficPolicy: ""
        externalIPs: [ ]