apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: iomete-istio
spec:
  interval: 5m
  releaseName: iomete-istio
  targetNamespace: istio-system
  install:
    createNamespace: true
  chart:
    spec:
      chart: iomete-istio
      version: 2.2.3
      sourceRef:
        kind: HelmRepository
        name: iomete
  values: {}